version: '3.1'

services:
  backend:
    image: armoryserver-expressjs
    build:
      context: $DOCKER_BUILD_DIR/ArmoryServer/
      dockerfile: $DOCKER_BUILD_DIR/ArmoryServer/Dockerfile
      args:
        ENV: $NODE_BUILD_ENV
    ports:
      - '8420:8420'
    volumes:
      - $DOCKER_SHARED_LOG_DIR:/etc/apache2/certs
