module.exports = {
  development:{
    PORT:9912,
    SSLCERTPATH:'/etc/apache2/certs/fullchain.pem',
    SSLKEYPATH:'/etc/apache2/certs/privkey.pem',
    ACCNTHOST:'api.outlawdesigns.io',
    ACCNTPORT:9661,
    ACCNTVERIFYEND:'/verify',
    AUTHHEADER:'auth_token',
    DBUSER:'root',
    DBHOST:'localhost',
    DBPASS:'example',
    DB_DB:'Armory_Refactor',
    DEFAULT_USER_ID:0
  },
  testing:{
    PORT:9912,
    SSLCERTPATH:'/etc/apache2/certs/fullchain.pem',
    SSLKEYPATH:'/etc/apache2/certs/privkey.pem',
    ACCNTHOST:'api.outlawdesigns.io',
    ACCNTPORT:9661,
    ACCNTVERIFYEND:'/verify',
    AUTHHEADER:'auth_token',
    DBUSER:'root',
    DBHOST:'localhost',
    DBPASS:'',
    DB_DB:'Armory_Test',
    DEFAULT_USER_ID:0
  },
  production:{
    PORT:8420,
    SSLCERTPATH:'/etc/apache2/certs/fullchain.pem',
    SSLKEYPATH:'/etc/apache2/certs/privkey.pem',
    ACCNTHOST:'api.outlawdesigns.io',
    ACCNTPORT:9661,
    ACCNTVERIFYEND:'/verify',
    AUTHHEADER:'auth_token',
    DBUSER:'root',
    DBHOST:'localhost',
    DBPASS:'',
    DB_DB:'Armory',
    DEFAULT_USER_ID:0
  }
};
